use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    // <repo>/strategies : one folder per strategy (recipe.toml + rust/mod.rs)
    let strategies_dir = Path::new(&manifest_dir)
        .join("..")
        .join("..")
        .join("strategies");
    let strategies_dir = fs::canonicalize(&strategies_dir).unwrap_or(strategies_dir);
    // New strategy folders must invalidate the registry even before their recipes are known.
    println!("cargo:rerun-if-changed={}", strategies_dir.display());
    let out_path = Path::new(&out_dir).join("strategies_registry.rs");

    let mut ids: Vec<String> = Vec::new();
    let mut plugin_ids: Vec<String> = Vec::new();

    if let Ok(entries) = fs::read_dir(&strategies_dir) {
        for entry in entries.flatten() {
            if !entry.path().is_dir() {
                continue;
            }
            let id = entry.file_name().to_string_lossy().to_string();
            if id.starts_with('_') {
                continue;
            }
            let recipe = entry.path().join("recipe.toml");
            if !recipe.is_file() {
                continue;
            }
            println!("cargo:rerun-if-changed={}", recipe.display());
            ids.push(id.clone());
            let rust_mod = entry.path().join("rust/mod.rs");
            if rust_mod.is_file() {
                println!("cargo:rerun-if-changed={}", rust_mod.display());
                plugin_ids.push(id);
            }
        }
    }

    ids.sort();
    plugin_ids.sort();

    let mut out = String::new();
    out.push_str("// @generated by build.rs - do not edit\n\n");
    out.push_str("use crate::data::MarketData;\n");
    out.push_str("use crate::recipe::{PluginSpec, Recipe};\n");
    out.push_str("use crate::runtime::{BatchContext, SignalBuffers};\n\n");

    out.push_str(
        "pub fn all_recipe_tomls() -> &'static [(&'static str, &'static str)] {\n    &[\n",
    );
    for id in &ids {
        out.push_str(&format!(
            "        (\"{id}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../strategies/{id}/recipe.toml\"))),\n"
        ));
    }
    out.push_str("    ]\n}\n\n");

    out.push_str("pub mod plugins {\n");
    for id in &plugin_ids {
        out.push_str(&format!(
            "    #[allow(non_snake_case)]\n    pub mod {id} {{\n        include!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../strategies/{id}/rust/mod.rs\"));\n    }}\n"
        ));
    }
    out.push_str("}\n\n");

    out.push_str(
        "pub fn build_plugin_signals(\n    plugin_type: &str,\n    data: &MarketData,\n    recipe: &Recipe,\n    genome: &[f64],\n    spec: &PluginSpec,\n    ctx: &BatchContext,\n    buffers: &mut SignalBuffers,\n) -> Result<(), String> {\n    match plugin_type {\n",
    );
    for id in &plugin_ids {
        out.push_str(&format!(
            "        \"{id}\" => {{\n            plugins::{id}::build_signals(data, recipe, genome, spec, ctx, buffers);\n            Ok(())\n        }}\n"
        ));
    }
    out.push_str("        other => Err(format!(\"unknown plugin type: {other}\")),\n    }\n}\n");

    let mut file = fs::File::create(&out_path).expect("create strategies_registry.rs");
    file.write_all(out.as_bytes())
        .expect("write strategies_registry.rs");
}
